# Melange build configuration for Node.js
# Uses Wolfi's pre-built nodejs package (CVE-patched within 24-48h)
# Much faster than building from source (~30s vs 30+ min)

package:
  name: node-minimal
  version: 22.12.0
  epoch: 0
  description: "Node.js runtime (Wolfi package wrapper)"
  copyright:
    - license: MIT
  dependencies:
    provides:
      - nodejs=${{package.version}}
    runtime:
      - nodejs-22

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - nodejs-22

pipeline:
  # Simple wrapper - just verify the package works
  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      # Node binary is already at /usr/bin/node from nodejs-22 package
      node --version
      echo "Node.js package verified"

# Automated version updates via wolfictl
update:
  enabled: true
  github:
    identifier: nodejs/node
    strip-prefix: v
    tag-filter: v22
    use-tag: true
