# Melange build configuration for Apache HTTPD
# Uses Wolfi's pre-built apache2 package (CVE-patched within 24-48h)
# This file enables wolfictl version tracking for daily updates

package:
  name: httpd-minimal
  version: 2.4.66
  epoch: 0
  description: "Apache HTTPD web server (Wolfi package wrapper)"
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - httpd=${{package.version}}
    runtime:
      - apache2

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-baselayout
      - apache2

pipeline:
  # Simple wrapper - just verify the package works
  - runs: |
      mkdir -p "${{targets.destdir}}/usr/sbin"
      # Apache binary is already at /usr/sbin/httpd from apache2 package
      httpd -v
      echo "Apache HTTPD package verified"

# Automated version updates via wolfictl
update:
  enabled: true
  github:
    identifier: apache/httpd
    strip-prefix: ""
    use-tag: true
