# Melange build configuration for Python from source
# Feature parity with Chainguard's Python image
# Built from source with full stdlib support

package:
  name: python-minimal
  version: 3.13.1
  epoch: 0
  description: "Python runtime built from source (Chainguard-equivalent)"
  copyright:
    - license: PSF-2.0
  dependencies:
    provides:
      - python3=${{package.version}}
      - python-3.13=${{package.version}}
      - python-3.13-base=${{package.version}}
    runtime:
      # Core C library
      - glibc
      - ld-linux
      - glibc-locale-posix
      # C++ support (for some extensions)
      - libgcc
      - libstdc++
      # Python module dependencies
      - libffi
      - zlib
      - libssl3
      - libcrypto3
      - readline
      - ncurses
      - ncurses-terminfo-base
      # Additional stdlib dependencies
      - libexpat1
      - libbz2-1
      - xz
      - libzstd1
      - mpdecimal
      - sqlite-libs
      - gdbm
      - libuuid

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      # Build toolchain
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      # Required build dependencies for full stdlib
      - zlib-dev
      - openssl-dev
      - libffi-dev
      - ncurses-dev
      - readline-dev
      - expat-dev
      - bzip2-dev
      - xz-dev
      - zstd-dev
      - mpdecimal-dev
      - sqlite-dev
      - gdbm-dev
      - util-linux-dev
      # For optimized builds
      - linux-headers

pipeline:
  # Clone CPython source from GitHub (no SHA256 needed - git verifies integrity)
  - uses: git-checkout
    with:
      repository: https://github.com/python/cpython.git
      tag: v${{package.version}}
      depth: 1

  # Configure with full stdlib support (matching Chainguard)
  - runs: |
      ./configure \
        --prefix=/usr \
        --enable-shared \
        --with-lto \
        --disable-test-modules \
        --without-ensurepip \
        --with-system-expat \
        --with-system-libmpdec \
        --with-dbmliborder=gdbm:ndbm \
        --enable-loadable-sqlite-extensions \
        --with-ssl-default-suites=openssl

  # Build Python
  - runs: |
      make -j$(nproc)

  # Install to destdir
  - runs: |
      make install DESTDIR="${{targets.destdir}}"

  # Clean up unnecessary files (keep stdlib intact)
  - runs: |
      cd "${{targets.destdir}}"

      # Remove test suites (not needed at runtime)
      rm -rf usr/lib/python3.13/test
      rm -rf usr/lib/python3.13/tests
      find . -type d -name 'idle_test' -exec rm -rf {} + 2>/dev/null || true

      # Remove IDE and dev tools
      rm -rf usr/lib/python3.13/idlelib
      rm -rf usr/lib/python3.13/tkinter
      rm -rf usr/lib/python3.13/turtledemo
      rm -rf usr/lib/python3.13/turtle.py
      rm -rf usr/lib/python3.13/lib-dynload/_tkinter*

      # Remove ensurepip (use Wolfi's py3-pip if needed)
      rm -rf usr/lib/python3.13/ensurepip

      # Remove deprecated modules
      rm -rf usr/lib/python3.13/lib2to3
      rm -rf usr/lib/python3.13/distutils

      # Remove static libraries
      find . -type f -name 'libpython*.a' -delete
      rm -rf usr/lib/pkgconfig

      # Remove header files (not needed at runtime)
      rm -rf usr/include

      # Remove documentation
      rm -rf usr/share/man
      rm -rf usr/share/doc

      # Remove dev tools from bin
      rm -f usr/bin/python3.13-config
      rm -f usr/bin/python3-config
      rm -f usr/bin/2to3*
      rm -f usr/bin/idle*

      # Compile .pyc files for faster startup
      "${{targets.destdir}}/usr/bin/python3.13" -m compileall -q \
        "${{targets.destdir}}/usr/lib/python3.13" 2>/dev/null || true

      # Strip binaries and shared libraries
      find . -type f -name '*.so*' -exec strip --strip-unneeded {} + 2>/dev/null || true
      strip --strip-unneeded usr/bin/python3.13 2>/dev/null || true

      # Create symlinks
      ln -sf python3.13 usr/bin/python3
      ln -sf python3.13 usr/bin/python

  # Verify the build (test more modules)
  - runs: |
      "${{targets.destdir}}/usr/bin/python3.13" -c "import sys; print(f'Python {sys.version}')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import ssl; print('SSL OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import json; print('JSON OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import hashlib; print('Hashlib OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import sqlite3; print('SQLite OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import xml.etree.ElementTree; print('XML OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import decimal; print('Decimal OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import bz2; print('BZ2 OK')"
      "${{targets.destdir}}/usr/bin/python3.13" -c "import lzma; print('LZMA OK')"

# Automated version updates via wolfictl
update:
  enabled: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.13
    use-tag: true
